### ISSUE TITLE
Streak / Time based actions

### ISSUE THREAD

**Issue by julienmarie** [Vojtanos/SimpleGamify#1]
I really like the simplicity of your solution.

Any plan on implementing time based challenges / streaks ?
I'm thinking something like this. Example:

```yaml
streak-form-fill:
  title: "Daily Filler"
  desc: "Fill a form daily to keep the streak alive."
  streak:
    action: fill-form
    count: 1
    period: 
      type: "daily"
      count: 7  # This denotes the number of consecutive periods the action must be performed
  points:
    xp: 10  # These points can be awarded for each successful completion or at the end of the streak
    streak-completion-bonus: 50  # Extra points awarded on successful completion of the streak
  custom:
    badge:
      title: "Consistent Filler"
      desc: "You filled a form daily for a week straight."
      img-url: "https://...image-link..."

```
